spring.application.name=tienlen-be
# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tienlen?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh

spring.datasource.username=tienlen_user
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Charset
spring.jpa.properties.hibernate.connection.characterEncoding=utf8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Bot external model
bot.external.url=http://127.0.0.1:8000/predict
